const packagesListData = [
  {
    id: 1,
    destination: "Sajek",
    image: require("../../assets/images/sajek.jpg"),
    title: "Dhaka",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
  },
  {
    id: 2,
    destination: "Rajshahi",
    image: require("../../assets/images/rajshahi.jpg"),
    title: "Sylhet",
    review: "10",
    day: "5",
    night: "4",
    price: "10000",
  },
  {
    id: 3,
    destination: "chittagong",
    image: require("../../assets/images/st.martin.jpg"),
    title: "Sajek Valley Experience",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
  },
  {
    id: 4,
    destination: "Sylhet",
    image: require("../../assets/images/package-img-1.png"),
    title: "Sajek Valley Experience",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
  },
  {
    id: 5,
    destination: "Bogalake",
    image: require("../../assets/images/bogalake.jpg"),
    title: "Sajek Valley Experience",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
  },
  {
    id: 6,
    destination: "Bandarban",
    image: require("../../assets/images/bandarban.jpg"),
    title: "Sajek Valley Experience",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
  },
];

export default packagesListData;
