const packagesListData = [
  {
    id: 1,
    destination: "Sajek",
    image: require("../../assets/images/package-img-1.png"),
    title: "Dhaka",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
  },
  {
    id: 2,
    destination: "Sylhet",
    image: require("../../assets/images/package-img-1.png"),
    title: "Sylhet",
    review: "10",
    day: "5",
    night: "4",
    price: "10000",
  },
  {
    id: 3,
    destination: "chittagong",
    image: require("../../assets/images/package-img-1.png"),
    title: "Sajek Valley Experience",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
  },
  {
    id: 4,
    destination: "Sylhet",
    image: require("../../assets/images/package-img-1.png"),
    title: "Sajek Valley Experience",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
  },
  {
    id: 5,
    destination: "Cox's Bazar",
    image: require("../../assets/images/package-img-1.png"),
    title: "Sajek Valley Experience",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
  },
  {
    id: 6,
    destination: "Cox's Bazar",
    image: require("../../assets/images/package-img-1.png"),
    title: "Sajek Valley Experience",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
  },
  {
    id: 7,
    destination: "Cox's Bazar",
    image: require("../../assets/images/package-img-1.png"),
    title: "Sajek Valley Experience",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
  },
  {
    id: 8,
    destination: "Cox's Bazar",
    image: require("../../assets/images/package-img-1.png"),
    title: "Sajek Valley Experience",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
  },
];

export default packagesListData;
