const packagesListData = [
  {
    id: 1,
    destination: "Sajek",
    image: require("../../assets/images/package-img-1.png"),
    title: "Tanguar TOITOIe with best adventures",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
    overview1: "Tanguar haor is a unique wetland ecosystem of national importance as it offers a combined view of submerged forest view, river view, and hill views. The Government is committed to preserving its natural resources and has taken several steps for the protection of this wetland as it was once subjected to over-exploitation of its natural resources. But now it has recovered its glory and offers a unique lifetime experience. The boat journey, the rapid change of the environment, the locals, the amazing and tranquil kingdom of water, the amazing hillside view —- all makes a deadly combination so charming, that you’ll be bound to return to that place whenever you get the chance.",
    overview2: "To offer you the most exotic experience of tanguar haor, we are offering a mighty vessel that will give you the experience of a lifetime. We’re certain that the natural charm and beauty, including our professional quality service, will definitely make you come back for more."
  },
  {
    id: 2,
    destination: "Sylhet",
    image: require("../../assets/images/bandarban.jpg"),
    title: "Breathtaking Bandarban Exploration",
    review: "10",
    day: "5",
    night: "4",
    price: "10000",
    overview1: "Bandarban Hill District is blissed with beauties & culture. You’ll find great mountain views in bandarban. It treks through virgin forests and chance to meet more than 15 tribes. Bandarban town which lies on the Sangu River, 92km from Chittagong. The river is the center of local life: epically long bamboo rafts, steered by a solitary boatman.",
    overview2: "There are so many amazing resorts in bandarban. The district is blessed with waterfalls, treks & unique lifestyle of tribal people. You’ll certainly enjoy the magical views from hills. The center of the Bandarban Hill District is the town of Bandarban. Here there is a harmonious mixture of the Moghs, devout Buddhists, and the Murangs who lure visitors with their legendary dances and traditional music."
  },
  {
    id: 3,
    destination: "chittagong",
    image: require("../../assets/images/bogalake.jpg"),
    title: "Bogalake Hiking Experience – Lake of Dragon",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
    overview1: "Tanguar haor is a unique wetland ecosystem of national importance as it offers a combined view of submerged forest view, river view, and hill views. The Government is committed to preserving its natural resources and has taken several steps for the protection of this wetland as it was once subjected to over-exploitation of its natural resources. But now it has recovered its glory and offers a unique lifetime experience. The boat journey, the rapid change of the environment, the locals, the amazing and tranquil kingdom of water, the amazing hillside view —- all makes a deadly combination so charming, that you’ll be bound to return to that place whenever you get the chance.",
    overview2: "To offer you the most exotic experience of tanguar haor, we are offering a mighty vessel that will give you the experience of a lifetime. We’re certain that the natural charm and beauty, including our professional quality service, will definitely make you come back for more."
  },
  {
    id: 4,
    destination: "Sylhet",
    image: require("../../assets/images/st.martin.jpg"),
    title: "St. Martin Island – Coral Blue Island",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
    overview1: "Saint Martin is one of the few coral islands in the world. Saint martin island in Bangladesh is called the blue heaven. Find the best hotels in st. martin & complete tour packages. Surrounding blue water, the island is way more gorgeous than you can imagine.",
    overview2: "Saint Martin tour is a small coral island in the heart of the Bay of Bengal. The island is made out of coral. This is the place where nature will definitely show you the definition of beauty. Enjoy an amazing ship journey on the blue Bay of Bengal. We designed the tour to make you feel every part of the beauty."
  },
  {
    id: 5,
    destination: "Cox's Bazar",
    image: require("../../assets/images/kuakata.jpg"),
    title: "Floating Market on Back water With Kuakata Beach",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
    overview1: "Kuakata offers a full view of the sunrise and sunset from the same white sandy beach in the water of the Bay of Bengal. All Kuakata hotels are not that good enough. Locally known as Shagor Kannya (Daughter of Ocean). the long strip of dark, marbled sand stretches for about 18 kilometers (11 mi). The long, wide beach at Kuakata has a typical natural setting. This sandy beach has gentle slopes into the Bay of Bengal. Kuakata is also a sanctuary for migratory winter birds.",
    overview2: "On the eastern end of the beach is Gongamati Reserved Forest, an evergreen mangrove forest and snippet of the original Kuakata. (When the Rakhines settled in the area in 1784, Kuakata was part of the larger Sundarbans forest. However, the Sundarbans is one-hour away by speedboat.) As a mangrove forest, Gongamati, like the Sundarbans, offers some protection against tidal surges. However, it too is being threatened by logging and deforestation. The best way to reach the forest is by foot or bike along the beach, where flag-flying fishing boats can be seen trawling the coast. Visiting Gangamati in the late afternoon is a perfect time to watch the sun cast shadows on the exposed mangrove roots."
  },
  {
    id: 6,
    destination: "Cox's Bazar",
    image: require("../../assets/images/rajshahi.jpg"),
    title: "Rajshahi City Tour",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
    overview1: "If you are a history lover; a thousand years old real stories fascinate you, this experience is designed exactly for you. Bangladesh holds the exciting stories of this Indian continent which will surely make travelers realize how to enrich the culture and civilization was back then! Let’s look into the stories you will experience in this tour.",
    overview2: "The flamboyant and delightfully maintained Tajhat Palace is arguably one of all the best rajbaris in Bangla Desh. The palace was made within the nineteenth century by Manna Lal Ray, a Hindu monger United Nations agency was forced to migrate from the geographical area and located his thanks to Citrus limonia. He eventually became an eminent jeweler, nonheritable tons of land, afterward won the title of the raja (landlord or ruler) and designed this large mansion. native villagers believe there’s a treasure hidden in its walls."
  },
  {
    id: 7,
    destination: "Cox's Bazar",
    image: require("../../assets/images/package-img-1.png"),
    title: "Tanguar 7 TOITOIe – The most luxurious house boat at Tanguar haor",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
    overview1: "Tanguar haor is a unique wetland ecosystem of national importance as it offers a combined view of submerged forest view, river view, and hill views. The Government is committed to preserving its natural resources and has taken several steps for the protection of this wetland as it was once subjected to over-exploitation of its natural resources. But now it has recovered its glory and offers a unique lifetime experience. The boat journey, the rapid change of the environment, the locals, the amazing and tranquil kingdom of water, the amazing hillside view —- all makes a deadly combination so charming, that you’ll be bound to return to that place whenever you get the chance.",
    overview2: "To offer you the most exotic experience of tanguar haor, we are offering a mighty vessel that will give you the experience of a lifetime. We’re certain that the natural charm and beauty, including our professional quality service, will definitely make you come back for more."
  },
  {
    id: 8,
    destination: "Cox's Bazar",
    image: require("../../assets/images/package-img-1.png"),
    title: "Tanguar 8 TOITOIe – The most luxurious house boat at Tanguar haor",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
    overview1: "Tanguar haor is a unique wetland ecosystem of national importance as it offers a combined view of submerged forest view, river view, and hill views. The Government is committed to preserving its natural resources and has taken several steps for the protection of this wetland as it was once subjected to over-exploitation of its natural resources. But now it has recovered its glory and offers a unique lifetime experience. The boat journey, the rapid change of the environment, the locals, the amazing and tranquil kingdom of water, the amazing hillside view —- all makes a deadly combination so charming, that you’ll be bound to return to that place whenever you get the chance.",
    overview2: "To offer you the most exotic experience of tanguar haor, we are offering a mighty vessel that will give you the experience of a lifetime. We’re certain that the natural charm and beauty, including our professional quality service, will definitely make you come back for more."
  },
  {
    id: 9,
    destination: "Cox's Bazar",
    image: require("../../assets/images/package-img-1.png"),
    title: "Tanguar 9 TOITOIe – The most luxurious house boat at Tanguar haor",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
    overview1: "Tanguar haor is a unique wetland ecosystem of national importance as it offers a combined view of submerged forest view, river view, and hill views. The Government is committed to preserving its natural resources and has taken several steps for the protection of this wetland as it was once subjected to over-exploitation of its natural resources. But now it has recovered its glory and offers a unique lifetime experience. The boat journey, the rapid change of the environment, the locals, the amazing and tranquil kingdom of water, the amazing hillside view —- all makes a deadly combination so charming, that you’ll be bound to return to that place whenever you get the chance.",
    overview2: "To offer you the most exotic experience of tanguar haor, we are offering a mighty vessel that will give you the experience of a lifetime. We’re certain that the natural charm and beauty, including our professional quality service, will definitely make you come back for more."
  },
  {
    id: 10,
    destination: "Cox's Bazar",
    image: require("../../assets/images/package-img-1.png"),
    title: "Tanguar 10 TOITOIe – The most luxurious house boat at Tanguar haor",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
    overview1: "Tanguar haor is a unique wetland ecosystem of national importance as it offers a combined view of submerged forest view, river view, and hill views. The Government is committed to preserving its natural resources and has taken several steps for the protection of this wetland as it was once subjected to over-exploitation of its natural resources. But now it has recovered its glory and offers a unique lifetime experience. The boat journey, the rapid change of the environment, the locals, the amazing and tranquil kingdom of water, the amazing hillside view —- all makes a deadly combination so charming, that you’ll be bound to return to that place whenever you get the chance.",
    overview2: "To offer you the most exotic experience of tanguar haor, we are offering a mighty vessel that will give you the experience of a lifetime. We’re certain that the natural charm and beauty, including our professional quality service, will definitely make you come back for more."
  },
  {
    id: 11,
    destination: "Cox's Bazar",
    image: require("../../assets/images/package-img-1.png"),
    title: "Tanguar 11 TOITOIe – The most luxurious house boat at Tanguar haor",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
    overview1: "Tanguar haor is a unique wetland ecosystem of national importance as it offers a combined view of submerged forest view, river view, and hill views. The Government is committed to preserving its natural resources and has taken several steps for the protection of this wetland as it was once subjected to over-exploitation of its natural resources. But now it has recovered its glory and offers a unique lifetime experience. The boat journey, the rapid change of the environment, the locals, the amazing and tranquil kingdom of water, the amazing hillside view —- all makes a deadly combination so charming, that you’ll be bound to return to that place whenever you get the chance.",
    overview2: "To offer you the most exotic experience of tanguar haor, we are offering a mighty vessel that will give you the experience of a lifetime. We’re certain that the natural charm and beauty, including our professional quality service, will definitely make you come back for more."
  },
  {
    id: 12,
    destination: "Cox's Bazar",
    image: require("../../assets/images/package-img-1.png"),
    title: "Tanguar 12 TOITOIe – The most luxurious house boat at Tanguar haor",
    review: "10",
    day: "5",
    night: "4",
    price: "5000",
    overview1: "Tanguar haor is a unique wetland ecosystem of national importance as it offers a combined view of submerged forest view, river view, and hill views. The Government is committed to preserving its natural resources and has taken several steps for the protection of this wetland as it was once subjected to over-exploitation of its natural resources. But now it has recovered its glory and offers a unique lifetime experience. The boat journey, the rapid change of the environment, the locals, the amazing and tranquil kingdom of water, the amazing hillside view —- all makes a deadly combination so charming, that you’ll be bound to return to that place whenever you get the chance.",
    overview2: "To offer you the most exotic experience of tanguar haor, we are offering a mighty vessel that will give you the experience of a lifetime. We’re certain that the natural charm and beauty, including our professional quality service, will definitely make you come back for more."
  },
];

export default packagesListData;
